# Generated by Django on 2026-08-31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AestheticAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('nature', 'Nature & Landscape'), ('anime', 'Anime & Illustration'), ('cinema', 'Cinema & Film Stills'), ('vintage', 'Vintage & Retro'), ('cyberpunk', 'Cyberpunk & Neon'), ('minimalist', 'Minimalist & Architecture')], default='nature', max_length=30)),
                ('image_url', models.URLField(blank=True, help_text='External image CDN URL', max_length=500)),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='assets/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Aesthetic Asset',
                'verbose_name_plural': 'Aesthetic Assets',
                'ordering': ['category', 'title'],
            },
        ),
        migrations.CreateModel(
            name='DevicePreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('phone', 'Phone'), ('tablet', 'Tablet'), ('desktop', 'Desktop / Laptop'), ('custom', 'Custom Dimensions')], default='phone', max_length=20)),
                ('width', models.PositiveIntegerField(help_text='Target pixel width (e.g. 1290)')),
                ('height', models.PositiveIntegerField(help_text='Target pixel height (e.g. 2796)')),
                ('icon', models.CharField(default='phone', help_text='Icon identifier (phone, tablet, desktop)', max_length=50)),
                ('is_default', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Device Preset',
                'verbose_name_plural': 'Device Presets',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LayoutPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('pattern_type', models.CharField(choices=[('mosaic', 'Dynamic Mosaic'), ('grid', 'Clean Uniform Grid'), ('shape', 'Shape Silhouette'), ('vintage', 'Vintage Gallery'), ('cinema', 'Cinematic Film')], default='mosaic', max_length=20)),
                ('cols', models.PositiveIntegerField(default=4)),
                ('rows', models.PositiveIntegerField(default=6)),
                ('gap', models.PositiveIntegerField(default=12, help_text='Gap between photo tiles in px')),
                ('padding', models.PositiveIntegerField(default=16, help_text='Canvas outer padding in px')),
                ('radius', models.PositiveIntegerField(default=18, help_text='Border radius in px')),
                ('bg_color', models.CharField(default='#0b0f19', help_text='Hex background color', max_length=25)),
                ('hero_ratio', models.CharField(default='2x2', help_text='Hero tile dimensions (e.g. 2x2, 3x3)', max_length=20)),
                ('filter_effect', models.CharField(blank=True, default='', help_text='CSS filter preset class', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('tag', models.CharField(blank=True, default='', help_text='Card badge label', max_length=50)),
                ('is_popular', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Layout Preset',
                'verbose_name_plural': 'Layout Presets',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WallpaperProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled Wallpaper', max_length=200)),
                ('custom_width', models.PositiveIntegerField(blank=True, null=True)),
                ('custom_height', models.PositiveIntegerField(blank=True, null=True)),
                ('configuration_json', models.JSONField(default=dict, help_text='Full state JSON (slots, images, styles, heroes, shapes)')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_preset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='wallpapers.devicepreset')),
                ('layout_preset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='wallpapers.layoutpreset')),
            ],
            options={
                'verbose_name': 'Wallpaper Project',
                'verbose_name_plural': 'Wallpaper Projects',
                'ordering': ['-updated_at'],
            },
        ),
    ]
